const CREATE = "CREATE";
const DELETE = "DELETE";
const FETCH_ALL = "FETCH_ALL";
const FETCH_CATEGORIES = "FETCH_CATEGORIES";
const UPDATE = "UPDATE";
export { CREATE, DELETE, FETCH_ALL, FETCH_CATEGORIES, UPDATE };
